import { MongoClient } from 'mongodb';
import { calculateApplicationScore, DEFAULT_CRITERIA } from '../src/lib/scoring';
import { generateReferenceNumber } from '../src/lib/security';
import { ApplicationDocument } from '../src/types';

const MONGODB_URI = process.env.MONGODB_URI;
const DB_NAME = process.env.MONGODB_DB_NAME || 'scholarship_db';

if (!MONGODB_URI) {
  console.error('❌ خطأ: يرجى تحديد MONGODB_URI قبل تشغيل بيانات التطوير.');
  process.exit(1);
}

const mockApplicantsData = [
  {
    fullName: 'أحمد محمود القرني',
    phoneCountryCode: '+962',
    phoneNumber: '501234567',
    email: 'ahmed.qarni@example.com',
    governorateOrCity: 'عمان',
    preferredContactMethod: 'phone' as const,
    institutionName: 'الجامعة الأردنية',
    studyLevel: 'بكالوريوس',
    major: 'هندسة مدنية',
    academicYearOrSemester: 'السنة الثالثة',
    enrollmentStatus: 'enrolled' as const,
    periodTuitionFee: 12000,
    amountAlreadyPaid: 0,
    confirmedExternalSupport: 0,
    isPaymentDeadlineNear: true,
    atRiskOfSuspension: true,
    otherScholarshipsOrDiscounts: 'none' as const,
    householdSize: 7,
    dependentsCount: 5,
    earnersCount: 0,
    otherStudyingFamilyMembersCount: 3,
    actualBreadwinner: 'father' as const,
    fatherStatus: 'unemployed' as const,
    motherStatus: 'unemployed' as const,
    alternativeSupportAvailable: 'no' as const,
    recentBreadwinnerLoss: false,
    income: {
      fatherIncome: { amount: 0, frequency: 'fixed' as const, isNetAvailable: true },
      motherIncome: null,
      studentIncome: null,
      otherFamilyContributions: null,
      pensions: null,
      regularCashAid: { amount: 800, frequency: 'fixed' as const, isNetAvailable: true },
      irregularAidAnnualEstimate: 1000,
    },
    hasSeasonalIncome: false,
    housingStatus: 'rented' as const,
    monthlyRent: 1500,
    recurringNecessaryMedicalExpenses: 400,
    necessaryCareObligations: null,
    otherFamilyEducationExpenses: 300,
    basicTransportExpenses: 350,
    otherObligations: [],
    recentJobLossOrIncomeDrop: true,
    recentJobLossDetails: 'فقدان رب الأسرة لعمله قبل 4 أشهر وتوقف الدخل الأساسي',
    deathOrAbsenceOfBreadwinnerImpact: false,
    healthOrCaregivingBurdenImpact: true,
    healthOrCaregivingDetails: 'علاج مستمر للوالد لأمراض مزمنة',
  },
  {
    fullName: 'سارة خالد العتيبي',
    phoneCountryCode: '+962',
    phoneNumber: '552345678',
    email: 'sara.otaibi@example.com',
    governorateOrCity: 'إربد',
    preferredContactMethod: 'whatsapp' as const,
    institutionName: 'جامعة اليرموك',
    studyLevel: 'بكالوريوس',
    major: 'تقنية معلومات',
    academicYearOrSemester: 'السنة الرابعة - تخرج',
    enrollmentStatus: 'enrolled' as const,
    periodTuitionFee: 14500,
    amountAlreadyPaid: 2000,
    confirmedExternalSupport: 0,
    isPaymentDeadlineNear: true,
    atRiskOfSuspension: true,
    otherScholarshipsOrDiscounts: 'none' as const,
    householdSize: 6,
    dependentsCount: 4,
    earnersCount: 0,
    otherStudyingFamilyMembersCount: 2,
    actualBreadwinner: 'mother' as const,
    fatherStatus: 'deceased' as const,
    motherStatus: 'unemployed' as const,
    alternativeSupportAvailable: 'partial' as const,
    recentBreadwinnerLoss: true,
    recentBreadwinnerLossDate: '2025-06-10',
    recentBreadwinnerLossImpact: 'وفاة الوالد وانتقال العبء للأسرة مع معاش تأميني محدود',
    income: {
      fatherIncome: null,
      motherIncome: null,
      studentIncome: null,
      otherFamilyContributions: null,
      pensions: { amount: 1900, frequency: 'fixed' as const, isNetAvailable: true },
      regularCashAid: null,
    },
    hasSeasonalIncome: false,
    housingStatus: 'rented' as const,
    monthlyRent: 1800,
    recurringNecessaryMedicalExpenses: 600,
    necessaryCareObligations: 200,
    otherFamilyEducationExpenses: 400,
    basicTransportExpenses: 300,
    otherObligations: [],
    recentJobLossOrIncomeDrop: false,
    deathOrAbsenceOfBreadwinnerImpact: true,
    deathOrAbsenceImpactDetails: 'وفاة الأب المعيل وانخفاض دخل الأسرة للمعاش فقط',
    healthOrCaregivingBurdenImpact: true,
  },
  {
    fullName: 'فيصل عبدالرحمن الدوسري',
    phoneCountryCode: '+962',
    phoneNumber: '543456789',
    email: 'faisal.doss@example.com',
    governorateOrCity: 'الكرك',
    preferredContactMethod: 'phone' as const,
    institutionName: 'جامعة مؤتة',
    studyLevel: 'دبلوم مشارك',
    major: 'إدارة سلاسل الإمداد',
    academicYearOrSemester: 'السنة الثانية',
    enrollmentStatus: 'enrolled' as const,
    periodTuitionFee: 9000,
    amountAlreadyPaid: 1000,
    confirmedExternalSupport: 0,
    isPaymentDeadlineNear: false,
    atRiskOfSuspension: false,
    otherScholarshipsOrDiscounts: 'none' as const,
    householdSize: 5,
    dependentsCount: 3,
    earnersCount: 1,
    otherStudyingFamilyMembersCount: 1,
    actualBreadwinner: 'student' as const,
    fatherStatus: 'unavailable' as const,
    motherStatus: 'unemployed' as const,
    alternativeSupportAvailable: 'no' as const,
    recentBreadwinnerLoss: false,
    income: {
      fatherIncome: null,
      motherIncome: null,
      studentIncome: { amount: 2200, frequency: 'fixed' as const, isNetAvailable: true },
      otherFamilyContributions: null,
      pensions: null,
      regularCashAid: null,
    },
    hasSeasonalIncome: false,
    housingStatus: 'rented' as const,
    monthlyRent: 1200,
    recurringNecessaryMedicalExpenses: 300,
    necessaryCareObligations: null,
    otherFamilyEducationExpenses: 200,
    basicTransportExpenses: 300,
    otherObligations: [],
    recentJobLossOrIncomeDrop: false,
    deathOrAbsenceOfBreadwinnerImpact: true,
    healthOrCaregivingBurdenImpact: false,
  },
  {
    fullName: 'مريم يوسف الزهراني',
    phoneCountryCode: '+962',
    phoneNumber: '564567890',
    email: 'maryam.zahrani@example.com',
    governorateOrCity: 'السلط',
    preferredContactMethod: 'whatsapp' as const,
    institutionName: 'جامعة البلقاء التطبيقية',
    studyLevel: 'بكالوريوس',
    major: 'تمريض',
    academicYearOrSemester: 'السنة الأولى',
    enrollmentStatus: 'enrolled' as const,
    periodTuitionFee: 11000,
    amountAlreadyPaid: 0,
    confirmedExternalSupport: 0,
    isPaymentDeadlineNear: true,
    atRiskOfSuspension: true,
    otherScholarshipsOrDiscounts: 'none' as const,
    householdSize: 8,
    dependentsCount: 6,
    earnersCount: 1,
    otherStudyingFamilyMembersCount: 4,
    actualBreadwinner: 'father' as const,
    fatherStatus: 'retired' as const,
    motherStatus: 'unemployed' as const,
    alternativeSupportAvailable: 'yes' as const,
    recentBreadwinnerLoss: false,
    income: {
      fatherIncome: null,
      motherIncome: null,
      studentIncome: null,
      otherFamilyContributions: null,
      pensions: { amount: 3200, frequency: 'fixed' as const, isNetAvailable: true },
      regularCashAid: null,
    },
    hasSeasonalIncome: false,
    housingStatus: 'owned' as const,
    monthlyRent: null,
    recurringNecessaryMedicalExpenses: 500,
    necessaryCareObligations: null,
    otherFamilyEducationExpenses: 800,
    basicTransportExpenses: 400,
    otherObligations: [],
    recentJobLossOrIncomeDrop: false,
    deathOrAbsenceOfBreadwinnerImpact: false,
    healthOrCaregivingBurdenImpact: true,
  },
  {
    fullName: 'عبدالله صالح الشمري',
    phoneCountryCode: '+962',
    phoneNumber: '595678901',
    email: 'abdullah.shammari@example.com',
    governorateOrCity: 'مادبا',
    preferredContactMethod: 'phone' as const,
    institutionName: 'الجامعة الهاشمية',
    studyLevel: 'بكالوريوس',
    major: 'محاسبة',
    academicYearOrSemester: 'السنة الثانية',
    enrollmentStatus: 'enrolled' as const,
    periodTuitionFee: 8500,
    amountAlreadyPaid: 0,
    confirmedExternalSupport: 0,
    isPaymentDeadlineNear: false,
    atRiskOfSuspension: false,
    otherScholarshipsOrDiscounts: 'none' as const,
    householdSize: 6,
    dependentsCount: 4,
    earnersCount: 0,
    otherStudyingFamilyMembersCount: 2,
    actualBreadwinner: 'father' as const,
    fatherStatus: 'unemployed' as const,
    motherStatus: 'unemployed' as const,
    alternativeSupportAvailable: 'no' as const,
    recentBreadwinnerLoss: false,
    income: {
      fatherIncome: { amount: 0, frequency: 'fixed' as const, isNetAvailable: true },
      motherIncome: null,
      studentIncome: null,
      otherFamilyContributions: null,
      pensions: null,
      regularCashAid: { amount: 1100, frequency: 'fixed' as const, isNetAvailable: true },
    },
    hasSeasonalIncome: false,
    housingStatus: 'rented' as const,
    monthlyRent: 1100,
    recurringNecessaryMedicalExpenses: 250,
    necessaryCareObligations: null,
    otherFamilyEducationExpenses: 200,
    basicTransportExpenses: 200,
    otherObligations: [],
    recentJobLossOrIncomeDrop: true,
    deathOrAbsenceOfBreadwinnerImpact: false,
    healthOrCaregivingBurdenImpact: false,
  },
  {
    fullName: 'نورة إبراهيم الغامدي',
    phoneCountryCode: '+962',
    phoneNumber: '536789012',
    email: 'noura.ghamdi@example.com',
    governorateOrCity: 'المفرق',
    preferredContactMethod: 'email' as const,
    institutionName: 'جامعة آل البيت',
    studyLevel: 'بكالوريوس',
    major: 'ذكاء اصطناعي وعلوم بيانات',
    academicYearOrSemester: 'السنة الثالثة',
    enrollmentStatus: 'enrolled' as const,
    periodTuitionFee: 15000,
    amountAlreadyPaid: 1500,
    confirmedExternalSupport: 0,
    isPaymentDeadlineNear: true,
    atRiskOfSuspension: true,
    otherScholarshipsOrDiscounts: 'none' as const,
    householdSize: 7,
    dependentsCount: 5,
    earnersCount: 1,
    otherStudyingFamilyMembersCount: 3,
    actualBreadwinner: 'father' as const,
    fatherStatus: 'working' as const,
    motherStatus: 'unemployed' as const,
    alternativeSupportAvailable: 'no' as const,
    recentBreadwinnerLoss: false,
    income: {
      fatherIncome: { amount: 2800, frequency: 'fixed' as const, isNetAvailable: true },
      motherIncome: null,
      studentIncome: null,
      otherFamilyContributions: null,
      pensions: null,
      regularCashAid: null,
    },
    hasSeasonalIncome: false,
    housingStatus: 'rented' as const,
    monthlyRent: 2000,
    recurringNecessaryMedicalExpenses: 300,
    necessaryCareObligations: null,
    otherFamilyEducationExpenses: 450,
    basicTransportExpenses: 350,
    otherObligations: [],
    recentJobLossOrIncomeDrop: false,
    deathOrAbsenceOfBreadwinnerImpact: false,
    healthOrCaregivingBurdenImpact: false,
  },
  {
    fullName: 'خالد ناصر السبيعي',
    phoneCountryCode: '+962',
    phoneNumber: '587890123',
    email: 'khaled.subaie@example.com',
    governorateOrCity: 'الزرقاء',
    preferredContactMethod: 'phone' as const,
    institutionName: 'جامعة العلوم والتكنولوجيا الأردنية',
    studyLevel: 'بكالوريوس',
    major: 'إعلام واتصال تسويقي',
    academicYearOrSemester: 'السنة الثانية',
    enrollmentStatus: 'enrolled' as const,
    periodTuitionFee: 10500,
    amountAlreadyPaid: 500,
    confirmedExternalSupport: 0,
    isPaymentDeadlineNear: false,
    atRiskOfSuspension: false,
    otherScholarshipsOrDiscounts: 'none' as const,
    householdSize: 5,
    dependentsCount: 3,
    earnersCount: 1,
    otherStudyingFamilyMembersCount: 2,
    actualBreadwinner: 'father' as const,
    fatherStatus: 'working' as const,
    motherStatus: 'unemployed' as const,
    alternativeSupportAvailable: 'no' as const,
    recentBreadwinnerLoss: false,
    income: {
      fatherIncome: { amount: 3500, frequency: 'fixed' as const, isNetAvailable: true },
      motherIncome: null,
      studentIncome: null,
      otherFamilyContributions: null,
      pensions: null,
      regularCashAid: null,
    },
    hasSeasonalIncome: false,
    housingStatus: 'owned' as const,
    monthlyRent: null,
    recurringNecessaryMedicalExpenses: 200,
    necessaryCareObligations: null,
    otherFamilyEducationExpenses: 300,
    basicTransportExpenses: 300,
    otherObligations: [],
    recentJobLossOrIncomeDrop: false,
    deathOrAbsenceOfBreadwinnerImpact: false,
    healthOrCaregivingBurdenImpact: false,
  },
  {
    fullName: 'ريم سلطان العلي',
    phoneCountryCode: '+962',
    phoneNumber: '508901234',
    email: 'reem.ali@example.com',
    governorateOrCity: 'العقبة',
    preferredContactMethod: 'whatsapp' as const,
    institutionName: 'الجامعة الألمانية الأردنية',
    studyLevel: 'بكالوريوس',
    major: 'لغة إنجليزية وترجمة',
    academicYearOrSemester: 'السنة الأولى',
    enrollmentStatus: 'enrolled' as const,
    periodTuitionFee: 7500,
    amountAlreadyPaid: 0,
    confirmedExternalSupport: 0,
    isPaymentDeadlineNear: false,
    atRiskOfSuspension: false,
    otherScholarshipsOrDiscounts: 'none' as const,
    householdSize: 6,
    dependentsCount: 4,
    earnersCount: 2,
    otherStudyingFamilyMembersCount: 2,
    actualBreadwinner: 'father' as const,
    fatherStatus: 'working' as const,
    motherStatus: 'working' as const,
    alternativeSupportAvailable: 'yes' as const,
    recentBreadwinnerLoss: false,
    income: {
      fatherIncome: { amount: 4500, frequency: 'fixed' as const, isNetAvailable: true },
      motherIncome: { amount: 3000, frequency: 'fixed' as const, isNetAvailable: true },
      studentIncome: null,
      otherFamilyContributions: null,
      pensions: null,
      regularCashAid: null,
    },
    hasSeasonalIncome: false,
    housingStatus: 'owned' as const,
    monthlyRent: null,
    recurringNecessaryMedicalExpenses: null,
    necessaryCareObligations: null,
    otherFamilyEducationExpenses: 500,
    basicTransportExpenses: 300,
    otherObligations: [],
    recentJobLossOrIncomeDrop: false,
    deathOrAbsenceOfBreadwinnerImpact: false,
    healthOrCaregivingBurdenImpact: false,
  },
];

async function seed() {
  console.log('🌱 بدء إدراج بيانات تجريبية للتطوير...');
  const client = new MongoClient(MONGODB_URI!);
  await client.connect();

  try {
    const db = client.db(DB_NAME);
    const appsCol = db.collection('applications');

    // Count existing
    const existing = await appsCol.countDocuments();
    if (existing > 0) {
      console.log(`⚠️ توجد بالفعل ${existing} طلبات في قاعدة البيانات.`);
      console.log('إذا رغبت في إعادة الإدراج بالكامل، نظف مجموعة applications أولاً.');
      return;
    }

    const docs: ApplicationDocument[] = mockApplicantsData.map((raw, idx) => {
      const uncoveredTuitionAmount = Math.max(
        0,
        raw.periodTuitionFee - raw.amountAlreadyPaid - raw.confirmedExternalSupport
      );

      const score = calculateApplicationScore(
        {
          householdSize: raw.householdSize,
          income: raw.income,
          hasSeasonalIncome: raw.hasSeasonalIncome,
          periodTuitionFee: raw.periodTuitionFee,
          amountAlreadyPaid: raw.amountAlreadyPaid,
          confirmedExternalSupport: raw.confirmedExternalSupport,
          uncoveredTuitionAmount,
          housingStatus: raw.housingStatus,
          monthlyRent: raw.monthlyRent,
          recurringNecessaryMedicalExpenses: raw.recurringNecessaryMedicalExpenses,
          necessaryCareObligations: raw.necessaryCareObligations,
          otherFamilyEducationExpenses: raw.otherFamilyEducationExpenses,
          basicTransportExpenses: raw.basicTransportExpenses,
          actualBreadwinner: raw.actualBreadwinner,
          fatherStatus: raw.fatherStatus,
          motherStatus: raw.motherStatus,
          alternativeSupportAvailable: raw.alternativeSupportAvailable,
          recentBreadwinnerLoss: raw.recentBreadwinnerLoss,
          recentBreadwinnerLossImpact: raw.recentBreadwinnerLossImpact,
        },
        DEFAULT_CRITERIA
      );

      // Distribute statuses across mock records
      let status: ApplicationDocument['status'] = 'new';
      let verificationStatus: ApplicationDocument['verificationStatus'] = 'unverified';
      if (idx === 0) {
        status = 'verified_eligible';
        verificationStatus = 'fully_verified';
      } else if (idx === 1) {
        status = 'verified_eligible';
        verificationStatus = 'fully_verified';
      } else if (idx === 2) {
        status = 'in_review';
        verificationStatus = 'partially_verified';
      }

      return {
        referenceNumber: generateReferenceNumber(),
        cycleId: '2026-FALL',
        idempotencyKey: `mock-seed-key-${idx}-${Date.now()}`,
        ...raw,
        uncoveredTuitionAmount,
        status,
        verificationStatus,
        eligibilityStatus: 'eligible',
        decisionStatus: 'pending',
        score,
        verifiedScore: verificationStatus === 'fully_verified' ? score : undefined,
        verificationChecklist: {
          tuitionFeeChecked: { verified: verificationStatus === 'fully_verified' },
          familyIncomeChecked: { verified: verificationStatus === 'fully_verified' },
          householdSizeChecked: { verified: verificationStatus === 'fully_verified' },
          breadwinnerStatusChecked: { verified: verificationStatus === 'fully_verified' },
          expensesChecked: { verified: verificationStatus === 'fully_verified' },
        },
        infoAccuracyAcknowledged: true,
        dataUseAcknowledged: true,
        willingToProvideDocsAcknowledged: true,
        noGuaranteeAcknowledged: true,
        createdAt: new Date(Date.now() - (idx * 3600000 * 5)),
        updatedAt: new Date(),
      };
    });

    await appsCol.insertMany(docs as unknown as Document[]);
    console.log(`✅ تم إدراج ${docs.length} طلبات تجريبية بنجاح.`);
  } finally {
    await client.close();
  }
}

seed().catch((err) => {
  console.error('❌ خطأ في إدراج البيانات:', err);
  process.exit(1);
});
